FROM golang

ENV NGROK_DOMAIN="ngrok.llovex.com"

RUN cd / && mkdir app && cd app && git clone https://github.com/inconshreveable/ngrok.git && cd ngrok && \
    openssl genrsa -out rootCA.key 2048 && \
    openssl req -x509 -new -nodes -key rootCA.key -subj "/CN=$NGROK_DOMAIN" -days 5000 -out rootCA.pem && \
    openssl genrsa -out device.key 2048 && \
    openssl req -new -key device.key -subj "/CN=$NGROK_DOMAIN" -out device.csr && \
    openssl x509 -req -in device.csr -CA rootCA.pem -CAkey rootCA.key -CAcreateserial -out device.crt -days 5000 && \
    cp rootCA.pem assets/client/tls/ngrokroot.crt -f && \
    cp device.crt assets/server/tls/snakeoil.crt -f && \
    cp device.key assets/server/tls/snakeoil.key -f && \
    sed -i "s#code.google.com/p#github.com/alecthomas#g" ./src/ngrok/log/logger.go && \
    make release-server  && GOOS=linux GOARCH=amd64 make release-client && \
    mv /app/ngrok/bin/ngrok* /usr/bin/ && \
    GOOS=darwin GOARCH=amd64 make release-client && \
    GOOS=windows GOARCH=amd64 make release-client && \
    GOOS=linux GOARCH=amd64 make release-client && \
    GOOS=windows GOARCH=386 make release-client && \
    GOOS=linux GOARCH=386 make release-client && \
    GOOS=darwin GOARCH=386 make release-client

CMD ngrokd -domain="ngrok.llovex.com" -httpAddr=":80" -tlsKey=/app/ngrok/assets/server/tls/snakeoil.key -tlsCrt=/app/ngrok/assets/server/tls/snakeoil.crt