FROM centos:centos7
MAINTAINER Jay <Jay@lloveu.cn>

ARG WORK_PATH=/app/

RUN yum -y update \
    && yum -y install fuse && yum -y install unzip \
    && curl https://rclone.org/install.sh | bash \
    && mkdir /one

COPY rclone.conf /root/.config/rclone/rclone.conf 

RUN  rclone mount myone:Documents /one --allow-other --uid 33 --gid 33 --daemon

ENTRYPOINT ["sleep","1000" ]
