apiVersion: v1
kind: Service
metadata:
  namespace: public-service
  labels:
    app: grafana
  name: grafana
  # namespace: monitoring
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  type: NodePort
  selector:
    app: grafana