apiVersion: v1
kind: Service
metadata:
  namespace: elk
  labels:
    app: splunk
  name: splunk-service
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  type: NodePort
  selector:
    app: splunk
