apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: ""
  name: alicloud-disk-bt
parameters:
  type: cloud
provisioner: alicloud/disk
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true  #可以扩容持久化券