apiVersion: v1
kind: Pod
metadata:
  name: exam
spec:
  tolerations:
  - key: "node-role.kubernetes.io/master"
    effect: "NoSchedule"
  containers:
  - name: exam
    image: "justliu/exam:1.0.1"
    ports:
    - containerPort: 7001
      name: web
    env:
    - name: aliyun_logs_catalina
      value: "stdout"
    - name: aliyun_logs_catalina_tags
      value: "exam"
