apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: openpitrix
    job: openpitrix-app-db-ctrl
    version: v0.3.5
  name: openpitrix-app-db-ctrl-job
  namespace: openpitrix-system
spec:
  backoffLimit: 20
  completions: 1
  parallelism: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: openpitrix
        job: openpitrix-app-db-ctrl
        job-name: openpitrix-app-db-ctrl-job
        version: v0.3.5
      name: openpitrix-app-db-ctrl
    spec:
      containers:
      - command:
        - flyway
        - -X
        - -url=jdbc:mysql://openpitrix-db.openpitrix-system.svc/app
        - -user=root
        - -validateOnMigrate=false
        - -locations=filesystem:/flyway/sql/app
        - migrate
        env:
        - name: FLYWAY_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password.txt
              name: mysql-pass
        image: openpitrix/openpitrix:flyway-v0.3.5
        imagePullPolicy: IfNotPresent
        name: openpitrix-app-db-ctrl
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - until nc -z openpitrix-db.openpitrix-system.svc 3306; do echo "waiting for
          mysql"; sleep 2; done;
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        name: wait-mysql
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
